#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
CoNLL-U fixing utility for the RĀBIṬA parsing workflow.

This script post-processes CoNLL-U files generated by CAMeL Parser in order
to improve compatibility with downstream annotation environments such as
INCEpTION.

In particular, it fixes malformed empty key-value pairs in the FEATS and
MISC columns, replacing values such as:

    key=

with:

    key=_

Usage examples:

    python conllu_fixing.py \
        --input input.conllu \
        --output output_fixed.conllu

    python conllu_fixing.py \
        --input-dir data/conllu \
        --output-dir data/conllu_fixed
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


__author__ = "Elisa Gugliotta"
__project__ = "RĀBIṬA"


EMPTY_VALUE = re.compile(r"(^|\|)([A-Za-z0-9_:-]+)=($|\|)")


def fix_kv_empty(field: str) -> str:
    """Replace empty key-value pairs in a CoNLL-U feature field.

    Examples:
        "pos=noun|gen=" -> "pos=noun|gen=_"
        "gen=|num=s" -> "gen=_|num=s"
    """
    if field in {"", "_"}:
        return field or "_"

    while True:
        new_field = EMPTY_VALUE.sub(
            lambda match: f"{match.group(1)}{match.group(2)}=_{match.group(3)}",
            field,
        )
        if new_field == field:
            break
        field = new_field

    return field


def fix_conllu_file(input_path: Path, output_path: Path) -> None:
    """Fix one CoNLL-U file and write the corrected version."""
    text = (
        input_path.read_text(encoding="utf-8", errors="replace")
        .replace("\r\n", "\n")
        .replace("\r", "\n")
    )

    output_lines: list[str] = []

    for line in text.split("\n"):
        if not line or line.startswith("#"):
            output_lines.append(line)
            continue

        cols = line.split("\t")

        # CoNLL-U requires exactly 10 columns.
        # If the line is malformed for another reason, preserve it unchanged.
        if len(cols) != 10:
            output_lines.append(line)
            continue

        # FEATS column
        cols[5] = fix_kv_empty(cols[5])

        # MISC column
        cols[9] = fix_kv_empty(cols[9])

        output_lines.append("\t".join(cols))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(output_lines), encoding="utf-8", newline="\n")


def fix_directory(input_dir: Path, output_dir: Path) -> None:
    """Fix all .conllu files in a directory."""
    output_dir.mkdir(parents=True, exist_ok=True)

    files = sorted(input_dir.glob("*.conllu"))
    if not files:
        raise FileNotFoundError(f"No .conllu files found in: {input_dir}")

    for file_path in files:
        out_path = output_dir / file_path.name
        fix_conllu_file(file_path, out_path)
        print(f"written {out_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fix malformed empty key-value pairs in CoNLL-U FEATS and MISC fields."
    )

    input_group = parser.add_mutually_exclusive_group(required=True)
    input_group.add_argument("--input", type=Path, help="Input .conllu file")
    input_group.add_argument("--input-dir", type=Path, help="Directory containing .conllu files")

    parser.add_argument("--output", type=Path, help="Output .conllu file")
    parser.add_argument("--output-dir", type=Path, help="Output directory for batch mode")

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if args.input:
        if not args.output:
            raise SystemExit("When using --input, you must also provide --output.")
        if not args.input.exists():
            raise FileNotFoundError(f"Input file not found: {args.input}")
        fix_conllu_file(args.input, args.output)
        print(f"written {args.output}")

    elif args.input_dir:
        if not args.output_dir:
            raise SystemExit("When using --input-dir, you must also provide --output-dir.")
        if not args.input_dir.exists():
            raise FileNotFoundError(f"Input directory not found: {args.input_dir}")
        fix_directory(args.input_dir, args.output_dir)


if __name__ == "__main__":
    main()
